image: docker:19.03.12

stages:
  - run
  - test

run:
  stage: run
  image: rust:latest
  before_script:
    - rustc -V
    - cargo --version
  script:
    - cargo run

test:
  stage: test
  image: rust:latest
  before_script:
    - rustc -V
    - cargo --version
  script:
    - cargo test
