[default]
address = "0.0.0.0"
port = 8000
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true
ident = "Kinesis API"
template_dir = "templates"

[default.limits]
forms = "64 kB"
json = "5 MiB"
msgpack = "5 MiB"
"file/jpg" = "20 MiB"
